### ISSUE TITLE
[Feature] scrollbar-thumb:rounded and scrollbar-track:rounded

### ISSUE THREAD

**Issue by robng** [adoxography/tailwind-scrollbar#1]
Hi!

First of all: neat little plugin, everything seems to be working nicely, so far.
I have one question though: Are you planning on adding :rounded modifiers for scrollbars? I'd love to see that feature.

I would have made a PR quickly, but since this is my first time fiddling with scrollbars, I figured I'd wait and see if you had something planned.

Thanks!

**Comment by adoxography** [comment]
Hey, glad you've been able to make use of the plugin!

I've sort of been going back and forth about whether or not to include rounded classes; while it's doable in webkit browsers, I haven't come across a way to round scrollbars in Firefox. For that reason, it seems to me that it might be a mistake to use a pure CSS approach to get round scrollbars, since you'll end up with pretty different looks across browsers. (For clarity, the reason I've got the hover styles in there when they don't affect Firefox is because Firefox applies a hover effect on its own.)

Happy to hear alternate viewpoints, though!

**Comment by robng** [comment]
Thinking about it right now, I can only see a small benefit for projects that exclusively rely on WebKit (or a derivative), such as projects based on NW.js or Electron and I am not sure, but this may be too much of an edge case to include.

Additionally, there is a slight risk that unexperienced users may not know that non-WebKit-browsers don't support rounded scrollbars.

However maybe, a 'webkit-rounded' class, instead of just 'rounded' class could be a solution? At least for those users who either don't mind slightly different looks between browsers or those that are limited to WebKit-rendering or the like.

**Comment by theophilelouvel** [comment]
Just wanted to drop by and thank you for the plugin! Works like a charm :) Cheers!
