### ISSUE TITLE
scrollbar width

### ISSUE THREAD

**Issue by Abdel3333** [adoxography/tailwind-scrollbar#11]
Hello. How to change the scrollbar with??

**Comment by adoxography** [comment]
As mentioned in the README,

> For every element that you want to style, add either the `.scrollbar` or `.scrollbar-thin` class.

`scrollbar` will give you a default-width scrollbar, and `scrollbar-thin` will give you a thinner one. The reason it's limited to these options is because of Firefox, which only allows `auto`, `thin`, and `none` for its [`scrollbar-width` property](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width).
