### ISSUE TITLE
scrollbar-color greyed out on chrome devtools and styles don't apply

### ISSUE THREAD

**Issue by hawkyre** [adoxography/tailwind-scrollbar#40]
I applied `scrollbar scrollbar-thumb-P scrollbar-track-p-light` in my html head but the scrollbar is still the default style.

In devtools it appears greyed out, as if the property didn't exist. Any ideas why?

![image](https://user-images.githubusercontent.com/50209142/184531044-2b5cba27-f1b2-45ff-bdd3-88851ed13c87.png)

**Comment by adoxography** [comment]
Yeah, there's two things going on here:

1. Firefox and Chrome use two very different approaches to scrollbars - that's what prompted me to write the plugin in the first place. Firefox uses the `scrollbar-width` and `scrollbar-color` properties, while Chrome uses a collection of pseudo elements (like `::-webkit-scrollbar-thumb`). The properties are getting greyed out here because Chrome doesn't recognize them (as expected).

2. You're not seeing any styling because your `<html>` element doesn't *have* any scrollbars. It's your `<body>` element that's overflowing, so it's the one that has the scrollbar. An irritating quirk in Firefox is that once you set those scrollbar properties, you can't unset them; for that reason, the utilities aren't inherited by children. You've gotta specify them exactly where you want them.
