### ISSUE TITLE
Only "scrollbar-track-gray-100" Working to set scrollbar track

### ISSUE THREAD

**Issue by pacifiquem** [adoxography/tailwind-scrollbar#50]
why I can't a custom scrollbar track like this scrollbar-track-black

**Comment by adoxography** [comment]
That should work. Some things to check:

- Make sure you also have `scrollbar` or `scrollbar-thin` on that element
- Make sure there's a scrollbar to begin with - i.e. if nothing's overflowing, you're not going to see a scrollbar.
- Make sure you're not overriding, instead of extending, your colours in your tailwind config. (If you've overridden them, classes like `bg-black` wouldn't work, either.)

If all of the above look good, drop me some code and I'll take a look. :)

**Comment by pacifiquem** [comment]
![image](https://user-images.githubusercontent.com/96472682/196398019-cb813d69-0e92-434d-bba5-88af5010430b.png)

--  that is body tag where I'm applying that

![image](https://user-images.githubusercontent.com/96472682/196398461-6db12cb1-8e8e-4901-a039-cfbd6451fd93.png)
 
 --   that is tailwind config

![image](https://user-images.githubusercontent.com/96472682/196398700-adca5f03-eeea-4ba5-80e9-423e58b7ade2.png)

--  that is the scrollbar

**Comment by adoxography** [comment]
That all looks good, so I took the liberty of scanning through one of your public repos to see if I could spot the issue. Looking at https://github.com/pacifiquem/megaFlix, I'm seeing that you're adding utilities to [`client/public/index.html`](https://github.com/pacifiquem/megaFlix/blob/23c01feb961c03b68ee68b8b665e9ba2686aca31/client/public/index.html#L15), but [`client/tailwind.config.js`](https://github.com/pacifiquem/megaFlix/blob/23c01feb961c03b68ee68b8b665e9ba2686aca31/client/tailwind.config.js#L3)'s `content` is only looking at `"./src/**/*.{js,jsx,ts,tsx}"`. You need to add `./public/index.html` if you want that file to be scanned as well. That'll also let you use `bg-black` there as well, instead of having to style directly.

**Comment by pacifiquem** [comment]
Okay Its fixed now
