### ISSUE TITLE
Styling not being applied to scrollable child elements

### ISSUE THREAD

**Issue by BlackBearFTW** [adoxography/tailwind-scrollbar#59]
Hi,

Currently the styling doesn't get applied to child elements. I was trying to define the scroll wheel style at the root of my project, but it doesn't get applied to all child components, like the official tailwind styling does. Because of that you must repeat your scroll wheel styling for every element. Could this be changed?

**Comment by adoxography** [comment]
This is partly a CSS thing - scrollbar properties aren't inherited. (This is true in Tailwind as well - the `overflow-*` family aren't inheritable.) You can run into issues when you try to fake inheritance here because (iirc) Firefox won't let you unset a scrollbar property once it's already been assigned.

However, it should be possible to get everything except `.scrollbar` and `.scrollbar-thin` to be inheritable, so you could define your colours, etc., on some high level element like the `body`, and then place `.scrollbar` on elements where you want a styled scrollbar. Something like:

```html
<body class="scrollbar-thumb-blue-700 scrollbar-track-blue-200">
    ...
    <div class="overflow-scroll scrollbar">
        ...
    </div>
    ...
    <div class="overflow-auto scrollbar">
        ...
    </div>
    ...
</body>
```

You still run into the issue of having `overflow-*` and `scrollbar` going hand in hand - might be a good use case for `@apply`.

**Comment by adoxography** [comment]
The above code will now work as of version 3.
