### ISSUE TITLE
[REQUEST] Add cursor option

### ISSUE THREAD

**Issue by Wolfleader101** [adoxography/tailwind-scrollbar#8]
Would be cool to be able to change cursor type for scrollbar so its a pointer.

**Comment by adoxography** [comment]
Hey, thanks for the suggestion. I think modifying the cursor type over a scrollbar might be a misstep for a couple of reasons:

1. It won't work cross-browser. While webkit-based browsers let you treat the scrollbar as a pseudoelement (allowing you to style it however you want), Firefox exposes a very limited selection of properties for modifying a scrollbar in the first place, all of which are available in this plugin. The issue of cross-browser consistency came up with regard to rounded scrollbars (see #1), which is why they're locked behind a flag.

2. It's my opinion that setting the cursor to `pointer` on a scrollbar is bad UX. The pointer means "link," and even if you expand that meaning to "clickable," that doesn't really describe a scrollbar. (Nothing happens if you just click on it.) If you're looking for a way to make it obvious that the scrollbar is interactive, I'd encourage looking to what the browsers do, which is change the hover colour. You can do that with this plugin using the `hover:scrollbar-thumb-*` classes.
