### ISSUE TITLE
Add gradient option

### ISSUE THREAD

**Issue by nikolailehbrink** [adoxography/tailwind-scrollbar#80]
Hi, it would be nice, If one is able to style the scrollbar with a gradient like in https://dev.to/susickypavel/how-to-make-scrollbar-with-changing-gradient-on-scroll-using-10-lines-of-css-42o2

**Comment by mujuni88** [comment]
+1

**Comment by adoxography** [comment]
As the primary purpose of this plugin is to keep things consistent cross-browser, I try to avoid exposing options that make scrollbars obviously different between Firefox and the rest. Since this effect is impossible in Firefox, I won't be adding it here. It looks easy enough to incorporate into your own CSS, though. :)
