### ISSUE TITLE
Feature Addition

### ISSUE THREAD

**Issue by Xevinaly** [adoxography/tailwind-scrollbar#9]
Hey, I didn't see an email associated with your github. I made some edits to this repo locally for a project. I was wondering if you would be interested in me adding them.
Changes:
 - added a scrollbar-none option to hide scrollbars
 - added  a scrollbar-border-color to give the border a color
 - added a scrollbar-border-width to give the border a width and solid style

**Comment by adoxography** [comment]
Hey, thanks for the feedback. Opening an issue here is the right place to bring this up. :)

The plugin missing a `scrollbar-none` class is definitely an oversight, though I'm wondering if it should really be `scrollbar-default`, since the idea of forcefully removing scrollbars is already handled by built-in classes like `overflow-hidden` and `overflow-visible`. I'm envisioning a class that would effectively negate the `scrollbar` or `scrollbar-thin` classes so that you could do something like `scrollbar lg:scrollbar-default`. I'd be happy to review a PR that includes something like that.

Beyond that, though, I really need to watch out for feature creep. I'm wary about adding classes like `*-border-*` for a couple of reasons:

- As I'm sure you've noticed, webkit browsers treat scrollbars as pseudoelements, which hypothetically means there's no end to the list of ways one *could* style a scrollbar. You've gotta put your foot down somewhere at the point where the plugin ends and individual user customization begins, and I think that's easily decided by the next point...
- Firefox treats scrollbars in a [much different way](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars), and the main "hook" for this plugin is the fact that it invisibly supports scrollbars cross-browser. Firefox limits you to styling the width and colour of a scrollbar, so modifying anything more than that is going to result in cross-browser inconsistencies.

I think there's room for exceptions to these rules; for example, the opt-in `scrollbar-rounded` classes are already part of the plugin. The difference there is that sharp corners in the scrollbar can really clash with rounded designs. I don't think having a scrollbar without a border hurts a design to quite the same extent.

**Comment by R4YM3** [comment]
Another person who would like this 😇.
For your context: track and body have the same background ground which i want to divide with a nice border.
