### ISSUE TITLE
Scrollbar-specific pointer events

### ISSUE THREAD

**Issue by Skippou** [adoxography/tailwind-scrollbar#94]
Hello,

I'm working on integrating a custom scrollbar using the Tailwind CSS `tailwind-scrollbar` plugin for a project that involves a map displayed within a `div`. The current implementation allows users to interact with the map by dragging, zooming, etc. However, I've encountered an issue where the pointer events (such as click and drag) intended for the scrollbar are also triggering interactions with the map underneath. This behavior leads to an undesirable user experience, as attempting to scroll through the content inadvertently interacts with the map.

Here is the example:

https://github.com/adoxography/tailwind-scrollbar/assets/64770056/4c303faf-b9a5-438f-82e4-e2d12eba4dd7

### Current Behavior
- The `div` containing the map has `pointer-events` enabled to allow user interactions with the map.
- When scrolling using the custom scrollbar, pointer events are passed through to the map, causing map interactions (e.g., dragging the map) instead of solely scrolling the content.

### Desired Outcome
- Retain interactive functionality of the map (allowing for clicks, drags, etc.).
- Isolate pointer events for the scrollbar so that interacting with the scrollbar does not trigger interactions with the map.

### Question
Is there a way to specifically assign or modify `pointer-events` for the custom scrollbar in a manner that does not affect the `div`'s content, particularly for interactive elements like a map? Ideally, users should be able to scroll using the custom scrollbar without unintentionally interacting with the map.

### Attempted Solutions
- I've tried adjusting the `pointer-events` property on the `div` but found that it either blocks all interactions with the map or allows both scrolling and map interactions simultaneously, which is not the desired behavior.

### Additional Context
- The project utilizes Next.js as the framework.
- Tailwind CSS for styling, with the `tailwind-scrollbar` plugin for custom scrollbars.

I appreciate any guidance or suggestions on how to achieve this separation of pointer event handling between the scrollbar and the map content. Thank you!

**Comment by adoxography** [comment]
First, to clear up some potential confusion: what you're working with here isn't so much a "custom scrollbar" as it is a custom**ized** (i.e. styled) scrollbar. Firefox (and now Chrome, as of v121) either render the scrollbar themselves or defer to the OS (I'm not actually sure which, and it might vary, for that matter) and, importantly, do not render it as a DOM element\*. Looking at the scrollbar in your example, it's clear that you're using one of these. For that reason, there's no `pointer-events` solution that would work here because there's no element to target `pointer-events` on.

_\* Chrome is still capable of rendering scrollbars as pseudoelements, which might be able to have a `pointer-events` solution. There's a [pre-release version of this plugin](https://github.com/adoxography/tailwind-scrollbar/issues/91#issuecomment-1913439800) that would enable you to force that behaviour. (If you went this route, the elements you'd want to target would be one or more of `::-webkit-scrollbar`, `::-webkit-scrollbar-thumb`, and `::-webkit-scrollbar-track`.) However, unless you're not planning to support Firefox, I wouldn't recommend this option, since Firefox doesn't support pseudoelement scrollbars at all and would still have the issue._

If it's possible in your application, your best bet would be to wrap the map element inside an extra container element, and have that container be the thing that has the scrollbar. At least in my own testing, the scrollbar won't send pointer events down to its element's children.

If you're unable or unwilling to use an extra container element, it looks to me like JavaScript's going to be your only option here. If it were me, I'd probably start with something like [this StackOverflow suggestion](https://stackoverflow.com/a/66143678), where you use the `scroll` event to let you know that mouse events should be temporarily ignored. Just a word to the wise, I wouldn't use something like [this suggestion](https://stackoverflow.com/a/33799265), involving comparing the mouse position with the element width, because some browser/OS combinations hide scrollbars when they're not used so they're not taken into account at all in the element width.

Good luck!

**Comment by Skippou** [comment]
Thank you very much for providing me with three solutions.

You truly are an expert in scrollbars. I was hoping for a simple, elegant solution. In my case, I think I will implement the suggestion from Stack Overflow.
